services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    networks:
      - lkforum_net

  backend:
    build: ./backend
    ports:
      - "8082:8080"
    env_file: ./backend/.env
    environment:
      REDIS_ADDR: redis:6379
      TZ: Asia/Ho_Chi_Minh
    depends_on:
      - redis
    networks:
      - lkforum_net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8082
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - lkforum_net
    restart: unless-stopped
networks:
  lkforum_net:

volumes:
  redis_data:
